package com.tars.service;

import com.tars.ai.PortraitGenerator;
import com.tars.ai.PortraitMatcher;
import com.tars.entity.bean.Application;
import com.tars.entity.bean.Portrait;
import com.tars.entity.bean.Position;
import com.tars.entity.bean.TAProfile;
import com.tars.entity.QueryCondition;
import com.tars.entity.dto.mo.ApplicationDTO;
import com.tars.entity.dto.mo.PosBriefDTO;
import com.tars.entity.dto.mo.PosDetailDTO;
import com.tars.entity.dto.mo.ProfileDTO;
import com.tars.mapper.AppMapper;
import com.tars.mapper.PosMapper;
import com.tars.mapper.ProfileMapper;
import com.tars.repository.JsonRepository;
import lombok.extern.slf4j.Slf4j;

import java.io.IOException;
import java.sql.Timestamp;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Service layer for Module Owner (MO) operations in the TA recruitment system.
 * <p>
 * This service provides comprehensive functionality for MOs to manage their positions
 * and review TA applications, including:
 * <ul>
 *   <li><b>Position Management</b>: Create, repost, view, and withdraw positions with AI-generated portraits</li>
 *   <li><b>Application Review</b>: View, filter, sort, and evaluate TA applications with AI-based recommendations</li>
 *   <li><b>Decision Making</b>: Offer or reject applications with feedback</li>
 *   <li><b>Workload Validation</b>: Check TA weekly workload constraints across multiple positions</li>
 * </ul>
 * </p>
 * <p>
 * <b>AI Integration:</b>
 * <ul>
 *   <li>{@link PortraitGenerator}: Generates vector embeddings from position descriptions</li>
 *   <li>{@link PortraitMatcher}: Calculates match scores between TA and position portraits for recommendation sorting</li>
 * </ul>
 * </p>
 * <p>
 * <b>Recommendation System:</b> When sorting applications by "recommend":
 * <ol>
 *   <li>Calculates match score between TA portrait and position portrait</li>
 *   <li>Checks if adding this position would exceed TA's max weekly workload</li>
 *   <li>Sorts non-exceeding TAs by match score (descending)</li>
 *   <li>Appends exceeding TAs at the end (sorted by score)</li>
 * </ol>
 * This ensures MOs see the best-fit candidates first while being aware of workload conflicts.
 * </p>
 * <p>
 * <b>Pagination:</b>
 * <ul>
 *   <li>Position listings: 9 records per page</li>
 *   <li>Application lists: 10 records per page</li>
 * </ul>
 * </p>
 * <p>
 * <b>Repost Feature:</b> Allows MOs to recreate a previous position while preserving:
 * <ul>
 *   <li>Original position ID (maintains application history linkage)</li>
 *   <li>Original creation timestamp</li>
 *   <li>Updates all other fields (description, requirements, dates, etc.)</li>
 * </ul>
 * </p>
 *
 * @author 477996850
 * @version 1.0.0
 * @since 2026/3/24
 * @see PortraitGenerator
 * @see PortraitMatcher
 */
@Slf4j
public class MOService {
    private final JsonRepository<Position> positionRepo = new JsonRepository<>(Position.class);

    private final JsonRepository<Application> applicationRepo = new JsonRepository<>(Application.class);

    private final JsonRepository<TAProfile> taProfileRepo = new JsonRepository<>(TAProfile.class);

    private final JsonRepository<Portrait> portraitRepo = new JsonRepository<>(Portrait.class);

    private final PortraitGenerator portraitGenerator = new PortraitGenerator();

    private final PortraitMatcher portraitMatcher = new PortraitMatcher();

    /** Page size for position listing queries (9 records per page) */
    private final int posPageSize = 9;

    /** Page size for application list queries (10 records per page) */
    private final int appPageSize = 10;

    /**
     * Creates a new position or reposts an existing one with AI-generated portrait.
     * <p>
     * This method supports two modes:
     * </p>
     * <p>
     * <b>Normal Creation Mode (repostId is null/empty):</b>
     * <ol>
     *   <li>Generates portrait from position data using {@link PortraitGenerator}</li>
     *   <li>Sets updateAt timestamp to current time</li>
     *   <li>Saves position (new UUID auto-generated by Position constructor)</li>
     *   <li>Saves portrait</li>
     * </ol>
     * </p>
     * <p>
     * <b>Repost Mode (repostId is provided):</b>
     * <ol>
     *   <li>Loads original position by reposId</li>
     *   <li>Preserves original position ID and createAt timestamp</li>
     *   <li>Updates all other fields from the provided position object</li>
     *   <li>Generates new portrait from updated position data</li>
     *   <li>Sets updateAt to current time</li>
     *   <li>Saves position (updates existing record due to preserved ID)</li>
     *   <li>Saves new portrait</li>
     * </ol>
     * </p>
     * <p>
     * <b>Use Case for Repost:</b> When an MO wants to re-open a position from a previous
     * semester with minor changes (e.g., updated dates, adjusted requirements) while
     * maintaining the same position identity for tracking purposes.
     * </p>
     *
     * @param position Position object with all required fields set
     * @param repostId  Original position ID for repost mode, or null/empty for new creation
     * @return true if operation succeeded, false if IO error occurred or original position not found (repost mode)
     * @see PortraitGenerator#generatePortrait(Position)
     */
    public boolean postPosition(Position position, String repostId) {
        try {
            Portrait portrait = portraitGenerator.generatePortrait(position);
            position.setPortraitId(portrait.getId());

            if (repostId != null && !repostId.trim().isEmpty()) {
                // Repost mode: load original position and preserve id and createAt
                Position originalPosition = positionRepo.getEntityById(repostId);
                
                if (originalPosition == null) {
                    log.error("Original position not found for repost, reposId: {}", repostId);
                    return false;
                }

                // Preserve original id and createAt
                String originalId = originalPosition.getId();
                Timestamp originalCreateAt = originalPosition.getCreateAt();

                // Update the position with preserved fields
                position.setId(originalId);
                position.setCreateAt(originalCreateAt);
                position.setUpdateAt(Timestamp.valueOf(LocalDateTime.now()));

                // Save the reposted position (update existing record)
                positionRepo.saveEntity(position);
                
                log.info("repost position success, positionId: {}, originalCreateAt: {}", 
                        originalId, originalCreateAt);
            } else {
                // Normal create mode: generate new id and timestamps
                position.setUpdateAt(Timestamp.valueOf(LocalDateTime.now()));
                positionRepo.saveEntity(position);
                
                log.info("create position success, positionId: {}", position.getId());
            }

            // Always save/update the portrait
            portraitRepo.saveEntity(portrait);

        } catch (IOException e) {
            log.error("create/repost position failed, positionId: {}, error message: {}", 
                    position.getId(), e.getMessage());
            return false;
        }
        return true;
    }


    /**
     * Retrieves a paginated list of positions posted by an MO (basic version).
     * <p>
     * This simple version returns all positions for the MO without filtering or sorting.
     * </p>
     *
     * @param userId ID of the MO user
     * @param page   Page number (1-based, clamped to minimum 1)
     * @return List of PosBriefDTO for the requested page
     * @see PosMapper#toMOPosBriefDTO(Position)
     */
    public List<PosBriefDTO> getPositionList(String userId, int page) {
        if (userId == null || userId.trim().isEmpty()) {
            log.warn("userId is null or empty");
            return List.of();
        }

        try {
            List<Position> positions = positionRepo.loadAllEntities();

            if (positions == null || positions.isEmpty()) {
                return List.of();
            }

            int pageNum = Math.max(page, 1);

            return positions.stream()
                    .filter(pos -> pos != null && userId.equals(pos.getPostUserId()))
                    .skip((long) (pageNum - 1) * posPageSize)
                    .limit(posPageSize)
                    .map(PosMapper.INSTANCE::toMOPosBriefDTO)
                    .filter(Objects::nonNull)
                    .toList();

        } catch (IOException e) {
            log.error("get position list failed, userId: {}, error message: {}", userId, e.getMessage());
            return List.of();
        }
    }

    /**
     * Retrieves a paginated list of positions posted by an MO with filtering and sorting.
     * <p>
     * This enhanced version supports:
     * <ul>
     *   <li><b>Filtering</b>: By position status (opened/closed/filled/withdrawn)</li>
     *   <li><b>Sorting</b>: By postDate or deadline</li>
     *   <li><b>Pagination</b>: Same as basic version</li>
     * </ul>
     * </p>
     * <p>
     * <b>Filter Options:</b>
     * <ul>
     *   <li>"opened" - Positions accepting applications (status=0)</li>
     *   <li>"closed" - Positions no longer accepting (status=1, note: code uses 1 for closed but Position defines 1=filled)</li>
     *   <li>"filled" - All required TAs have been offered (status=2)</li>
     *   <li>"withdrawn" - Cancelled positions (status=3)</li>
     *   <li>Other values - No filter applied</li>
     * </ul>
     * </p>
     * <p>
     * <b>Sort Options:</b>
     * <ul>
     *   <li>"postDate" - By posting date (descending, newest first)</li>
     *   <li>"deadline" - By application deadline (ascending, earliest first)</li>
     *   <li>Other values - No sorting applied (default order)</li>
     * </ul>
     * </p>
     * <p>
     * <b>Null Handling:</b> Date comparisons use {@link Comparator#nullsLast(Comparator)}
     * to ensure positions with null dates appear at the end of sorted results.
     * </p>
     *
     * @param userId    ID of the MO user
     * @param condition Query conditions containing filter, order, and page parameters
     * @return List of PosBriefDTO for the requested page with applied filters and sorting
     * @see QueryCondition
     * @see PosMapper#toMOPosBriefDTO(Position)
     */
    public List<PosBriefDTO> getPositionList(String userId, QueryCondition condition) {
        if (userId == null || userId.trim().isEmpty()) {
            log.warn("userId is null or empty");
            return List.of();
        }

        try {
            List<Position> positions = positionRepo.loadAllEntities();

            if (positions == null || positions.isEmpty()) {
                return List.of();
            }

            int pageNum = Math.max(condition.getPage(), 1);

            Stream<Position> posStream = positions.stream()
                    .filter(pos -> pos != null && userId.equals(pos.getPostUserId()));

            posStream = switch (condition.getFilter()) {
                case "opened" -> posStream.filter(pos -> pos.getStatus() == 0);
                case "closed" -> posStream.filter(pos -> pos.getStatus() == 1);
                case "filled" -> posStream.filter(pos -> pos.getStatus() == 2);
                case "withdrawn" -> posStream.filter(pos -> pos.getStatus() == 3);
                default -> posStream;
            };

            posStream = switch (condition.getOrder()) {
                case "postDate" -> posStream.sorted(Comparator.comparing(Position::getPostDate, Comparator.nullsLast(Comparator.naturalOrder())).reversed());
                case "deadline" -> posStream.sorted(Comparator.comparing(Position::getDeadline, Comparator.nullsLast(Comparator.naturalOrder())));
                default -> posStream;
            };

            return posStream.skip((long) (pageNum - 1) * posPageSize)
                    .limit(posPageSize)
                    .map(PosMapper.INSTANCE::toMOPosBriefDTO)
                    .filter(Objects::nonNull)
                    .toList();

        } catch (IOException e) {
            log.error("get position list failed, userId: {}, error message: {}", userId, e.getMessage());
            return List.of();
        }
    }


    /**
     * Calculates the total number of pages for MO's positions with filtering.
     * <p>
     * This method applies the same status filter as {@link #getPositionList(String, QueryCondition)}
     * before counting to ensure accurate pagination.
     * </p>
     *
     * @param userId    ID of the MO user
     * @param condition Query conditions containing filter parameter
     * @return Total number of pages after applying filter (0 if no positions found)
     */
    public long getPositionPages(String userId, QueryCondition condition) {
        if (userId == null || userId.trim().isEmpty()) {
            log.warn("userId is null or empty");
            return 0;
        }

        try {
            List<Position> positions = positionRepo.loadAllEntities();

            if (positions == null || positions.isEmpty()) {
                return 0;
            }

            Stream<Position> posStream = positions.stream()
                    .filter(pos -> pos != null && userId.equals(pos.getPostUserId()));
            posStream = switch (condition.getFilter()) {
                case "opened" -> posStream.filter(pos -> pos.getStatus() == 0);
                case "closed" -> posStream.filter(pos -> pos.getStatus() == 1);
                case "filled" -> posStream.filter(pos -> pos.getStatus() == 2);
                case "withdrawn" -> posStream.filter(pos -> pos.getStatus() == 3);
                default -> posStream;
            };

            long positionCount = posStream.count();

            return positionCount % posPageSize == 0 ? positionCount / posPageSize : positionCount / posPageSize + 1;
        } catch (IOException e) {
            log.error("get position pages failed, userId: {}, error message: {}", userId, e.getMessage());
            return 0;
        }
    }

    /**
     * Retrieves detailed information for a specific position.
     * <p>
     * This method returns complete position details including all statistics
     * (requiredNum, offeredNum, appliedNum, rejectedNum) for MO management.
     * </p>
     *
     * @param posId ID of the position to retrieve
     * @return PosDetailDTO with full position information, or null if not found
     * @see PosMapper#toMOPosDetailDTO(Position)
     */
    public PosDetailDTO getPosition(String posId) {
        if (posId == null || posId.trim().isEmpty()) {
            log.warn("posId is null or empty");
            return null;
        }

        try {
            Position position = positionRepo.getEntityById(posId);
            if (position == null) {
                log.warn("position not found, posId: {}", posId);
                return null;
            }
            return PosMapper.INSTANCE.toMOPosDetailDTO(position);
        } catch (IOException e) {
            log.error("get position failed, posId: {}, error message: {}", posId, e.getMessage());
            return null;
        }
    }


    /**
     * Retrieves a paginated list of applications for a position with filtering, sorting, and AI-based recommendation.
     * <p>
     * This is the most complex method in MOService, providing comprehensive application review capabilities:
     * <ul>
     *   <li><b>Filtering</b>: By application status (opened/offered/rejected)</li>
     *   <li><b>Sorting</b>: Multiple options including AI-powered recommendation</li>
     *   <li><b>Workload Validation</b>: Checks if TA would exceed max weekly workload</li>
     *   <li><b>Profile Integration</b>: Combines application data with TA profile information</li>
     * </ul>
     * </p>
     * <p>
     * <b>Filter Options:</b>
     * <ul>
     *   <li>"opened" - Applications awaiting review (status=0)</li>
     *   <li>"offered" - Applications with offers extended (status=1)</li>
     *   <li>"rejected" - Declined applications (status=2)</li>
     *   <li>Other values - Excludes withdrawn applications (status=3), shows all others</li>
     * </ul>
     * </p>
     * <p>
     * <b>Sort Options:</b>
     * <ul>
     *   <li>"recommend" - AI-based recommendation with workload validation (detailed below)</li>
     *   <li>"applyAt" - By application submission time (ascending, oldest first)</li>
     *   <li>Other values - No sorting applied</li>
     * </ul>
     * </p>
     * <p>
     * <b>Recommendation Algorithm (order="recommend"):</b>
     * <ol>
     *   <li>Load position and its portrait</li>
     *   <li>Generate weekly periods from position start/end dates</li>
     *   <li>For each application:
     *     <ul>
     *       <li>Retrieve TA profile and check max weekly workload</li>
     *       <li>Get all other positions where TA has been offered</li>
     *       <li>Check if adding this position would exceed workload in any week</li>
     *       <li>If exceeds: add to exceedList</li>
     *       <li>If not exceeds: calculate match score, add to notExceedList</li>
     *     </ul>
     *   </li>
     *   <li>Sort notExceedList by match score (descending)</li>
     *   <li>Append exceedList at the end (also sorted by score)</li>
     *   <li>Apply pagination</li>
     * </ol>
     * </p>
     * <p>
     * <b>Workload Check Logic:</b>
     * For each week in the position duration:
     * <ul>
     *   <li>Calculate total workload = new position workload + sum of all offered positions overlapping that week</li>
     *   <li>If total > TA's maxWeeklyWorkload for any week → exceeds</li>
     * </ul>
     * </p>
     * <p>
     * <b>Pagination:</b> Applied after sorting, uses appPageSize (10 records per page).
     * </p>
     *
     * @param posId     ID of the position
     * @param condition Query conditions containing filter, order, and page parameters
     * @return List of ApplicationDTO for the requested page
     * @see AppMapper#toAppDTO(Application, TAProfile)
     * @see #checkWorkloadExceeds(List, Position, List, float)
     */
    public List<ApplicationDTO> getAppList(String posId, QueryCondition condition) {
        if (posId == null || posId.trim().isEmpty()) {
            log.warn("posId is null or empty");
            return List.of();
        }

        try {
            List<Application> applications = applicationRepo.loadAllEntities();
            List<TAProfile> taProfiles = taProfileRepo.loadAllEntities();

            if (applications == null || applications.isEmpty()) {
                return List.of();
            }

            Map<String, TAProfile> profileMap = taProfiles.stream()
                    .filter(profile -> profile != null && profile.getUserId() != null)
                    .collect(java.util.stream.Collectors.toMap(
                            TAProfile::getUserId,
                            profile -> profile,
                            (existing, replacement) -> existing
                    ));

            int pageNum = Math.max(condition.getPage(), 1);

            Stream<Application> baseAppStream = applications.stream()
                    .filter(app -> app != null && posId.equals(app.getPositionId()) && app.getStatus() != 3);

            baseAppStream = switch (condition.getFilter()) {
                case "opened" -> baseAppStream.filter(app -> app.getStatus() == 0);
                case "offered" -> baseAppStream.filter(app -> app.getStatus() == 1);
                case "rejected" -> baseAppStream.filter(app -> app.getStatus() == 2);
                default -> baseAppStream;
            };


            List<Application> finalApplications;

            if ("recommend".equals(condition.getOrder())) {
                try {
                    Position position = positionRepo.getEntityById(posId);
                    if (position == null) {
                        log.warn("Position not found for recommendation, posId: {}", posId);
                        finalApplications = baseAppStream.toList();
                    } else {
                        List<Application> allApplications = applicationRepo.loadAllEntities();
                        Map<String, List<Application>> userOfferedAppsMap = allApplications.stream()
                                .filter(app -> app != null && app.getStatus() == 1)
                                .collect(Collectors.groupingBy(Application::getUserId));

                        List<LocalDate> weeklyPeriods = generateWeeklyPeriods(
                                position.getStartDate().toLocalDateTime().toLocalDate(),
                                position.getEndDate().toLocalDateTime().toLocalDate()
                        );

                        Portrait positionPortrait = portraitRepo.getEntityById(position.getPortraitId());

                        List<Application> appList = baseAppStream.toList();

                        List<Application> notExceedList = new java.util.ArrayList<>();
                        List<Application> exceedList = new java.util.ArrayList<>();

                        Map<String, Double> scoreCache = new java.util.HashMap<>();

                        for (Application app : appList) {
                            String userId = app.getUserId();
                            TAProfile profile = profileMap.get(userId);

                            if (profile == null) {
                                log.debug("Profile not found for userId: {}", userId);
                                continue;
                            }

                            float maxWeeklyWorkload = profile.getMaxWeeklyWorkload();

                            List<Application> userOfferedApps = userOfferedAppsMap.getOrDefault(userId, List.of());

                            boolean exceeds = checkWorkloadExceeds(
                                    userOfferedApps,
                                    position,
                                    weeklyPeriods,
                                    maxWeeklyWorkload);

                            if (exceeds) {
                                exceedList.add(app);
                            } else {
                                notExceedList.add(app);

                                if (!scoreCache.containsKey(userId)) {
                                    Portrait taPortrait = null;
                                    if (profile.getPortraitId() != null) {
                                        taPortrait = portraitRepo.getEntityById(profile.getPortraitId());
                                    }

                                    double score = 0.0;
                                    if (taPortrait != null && positionPortrait != null) {
                                        score = portraitMatcher.calculateMatchScore(taPortrait, positionPortrait);
                                    }
                                    scoreCache.put(userId, score);
                                }
                            }
                        }

                        notExceedList.sort((app1, app2) -> {
                            double score1 = scoreCache.getOrDefault(app1.getUserId(), 0.0);
                            double score2 = scoreCache.getOrDefault(app2.getUserId(), 0.0);
                            return Double.compare(score2, score1);
                        });

                        List<Application> sortedList = new ArrayList<>(notExceedList);
                        sortedList.addAll(exceedList);

                        finalApplications = sortedList;
                    }


                } catch (IOException e) {
                    log.error("Recommend sorting failed, error message: {}", e.getMessage());
                    finalApplications = baseAppStream.toList();
                }
            } else {
                Comparator<Application> comparator = switch (condition.getOrder()) {
                    case "applyAt" -> Comparator.comparing(Application::getApplyAt);
                    default -> (a1, a2) -> 0;
                };

                finalApplications = baseAppStream.sorted(comparator).toList();
            }

            return finalApplications.stream()
                    .map(app -> {
                        TAProfile profile = profileMap.get(app.getUserId());
                        if (profile == null) {
                            log.debug("TAProfile not found for userId: {}", app.getUserId());
                            return null;
                        }
                        return AppMapper.INSTANCE.toAppDTO(app, profile);
                    })
                    .filter(Objects::nonNull)
                    .skip((long) (pageNum - 1) * appPageSize)
                    .limit(appPageSize)
                    .toList();

        } catch (IOException e) {
            log.error("get application list failed, posId: {}, error message: {}", posId, e.getMessage());
            return List.of();
        }
    }


    /**
     * Calculates the total number of pages for applications with filtering.
     * <p>
     * This method applies the same status filter as {@link #getAppList(String, QueryCondition)}
     * before counting to ensure accurate pagination. Note: Withdrawn applications (status=3)
     * are always excluded.
     * </p>
     *
     * @param posId     ID of the position
     * @param condition Query conditions containing filter parameter
     * @return Total number of pages after applying filter (0 if no applications found)
     */
    public long getAppPages(String posId, QueryCondition condition) {
        if (posId == null || posId.trim().isEmpty()) {
            log.warn("posId is null or empty");
            return 0;
        }

        try {
            List<Application> applications = applicationRepo.loadAllEntities();

            if (applications == null || applications.isEmpty()) {
                return 0;
            }

            Stream<Application> appStream = applications.stream()
                    .filter(app -> app != null && posId.equals(app.getPositionId()) && app.getStatus() != 3);

            appStream = switch (condition.getFilter()) {
                case "opened" -> appStream.filter(app -> app.getStatus() == 0);
                case "offered" -> appStream.filter(app -> app.getStatus() == 1);
                case "rejected" -> appStream.filter(app -> app.getStatus() == 2);
                default -> appStream;
            };

            long appCount = appStream.count();

            return appCount % appPageSize == 0 ? appCount / appPageSize : appCount / appPageSize + 1;
        } catch (IOException e) {
            log.error("get application pages failed, posId: {}, error message: {}", posId, e.getMessage());
            return 0;
        }
    }

    /**
     * Verifies if a user is the owner of a position.
     * <p>
     * This security check ensures that only the MO who posted a position can perform
     * management operations on it (view applications, make decisions, withdraw, etc.).
     * </p>
     *
     * @param posId  ID of the position to verify
     * @param userId ID of the user claiming ownership
     * @return true if user is the position owner, false otherwise
     */
    public boolean verifyPositionOwner(String posId, String userId) {
        if (posId == null || posId.trim().isEmpty() || userId == null || userId.trim().isEmpty()) {
            log.warn("posId or userId is null or empty");
            return false;
        }

        try {
            Position position = positionRepo.getEntityById(posId);
            if (position == null) {
                log.warn("position not found, posId: {}", posId);
                return false;
            }
            return userId.equals(position.getPostUserId());
        } catch (IOException e) {
            log.error("verify position owner failed, posId: {}, userId: {}, error message: {}",
                    posId, userId, e.getMessage());
            return false;
        }
    }

    /**
     * Retrieves a TA's profile with application feedback for MO review.
     * <p>
     * This method combines TA profile information with the feedback from their application
     * to provide MOs with a complete view during the review process.
     * </p>
     *
     * @param profileId     ID of the TA profile
     * @param applicationId ID of the application (for retrieving feedback)
     * @return ProfileDTO with profile data and feedback, or null if profile not found
     * @see ProfileMapper#toMOProfileDTO(TAProfile, String)
     */
    public ProfileDTO getProfile(String profileId, String applicationId) {
        if (profileId == null || profileId.trim().isEmpty()) {
            log.warn("profile is null or empty");
            return null;
        }

        try {
            TAProfile profile = taProfileRepo.getEntityById(profileId);
            if (profile == null) {
                log.warn("profile not found, profileId: {}", profileId);
                return null;
            }
            Application application = applicationRepo.getEntityById(applicationId);
            String feedback = application != null ? application.getFeedback() : "";
            return ProfileMapper.INSTANCE.toMOProfileDTO(profile, feedback);
        } catch (IOException e) {
            log.error("get ta profile failed, profileId: {}, error message: {}", profileId, e.getMessage());
            return null;
        }
    }

    /**
     * Extends an offer to a TA applicant and updates position statistics.
     * <p>
     * This method performs the following actions:
     * <ol>
     *   <li>Validates application exists and has status=0 (applied)</li>
     *   <li>Sets application status to 1 (offered)</li>
     *   <li>Saves feedback (if provided)</li>
     *   <li>Increments position's offeredNum counter</li>
     *   <li>If offeredNum >= requiredNum, sets position status to 1 (filled)</li>
     * </ol>
     * </p>
     * <p>
     * <b>Validation:</b> Only applications with status=0 (applied) can be offered.
     * Already offered/rejected/withdrawn applications cannot be re-offered.
     * </p>
     *
     * @param appId    ID of the application to offer
     * @param feedback Optional feedback message to the TA
     * @return true if offer succeeded, false if validation failed or IO error occurred
     */
    public boolean offerApplication(String appId, String feedback) {
        if (appId == null || appId.trim().isEmpty()) {
            log.warn("appId is null or empty");
            return false;
        }

        try {
            Application application = applicationRepo.getEntityById(appId);
            if (application == null) {
                log.warn("Application not found, appId: {}", appId);
                return false;
            }

            if (application.getStatus() != 0) {
                log.warn("Application status is not 'applied', appId: {}, status: {}", appId, application.getStatus());
                return false;
            }

            application.setStatus(1);
            application.setFeedback(feedback != null ? feedback : "");
            applicationRepo.saveEntity(application);

            Position position = positionRepo.getEntityById(application.getPositionId());
            if (position != null) {
                position.setOfferedNum(position.getOfferedNum() + 1);

                if (position.getOfferedNum() >= position.getRequiredNum()) {
                    position.setStatus(1);
                }

                positionRepo.saveEntity(position);
            }

            log.info("Offer application success, appId: {}", appId);
            return true;
        } catch (IOException e) {
            log.error("Offer application failed, appId: {}, error: {}", appId, e.getMessage());
            return false;
        }
    }

    /**
     * Rejects a TA application and updates position statistics.
     * <p>
     * This method performs the following actions:
     * <ol>
     *   <li>Validates application exists and has status=0 (applied)</li>
     *   <li>Sets application status to 2 (rejected)</li>
     *   <li>Saves feedback (if provided)</li>
     *   <li>Increments position's rejectedNum counter</li>
     * </ol>
     * </p>
     * <p>
     * <b>Validation:</b> Only applications with status=0 (applied) can be rejected.
     * Already offered/rejected/withdrawn applications cannot be re-rejected.
     * </p>
     *
     * @param appId    ID of the application to reject
     * @param feedback Optional feedback message explaining rejection reason
     * @return true if rejection succeeded, false if validation failed or IO error occurred
     */
    public boolean rejectApplication(String appId, String feedback) {
        if (appId == null || appId.trim().isEmpty()) {
            log.warn("appId is null or empty");
            return false;
        }

        try {
            Application application = applicationRepo.getEntityById(appId);
            if (application == null) {
                log.warn("Application not found, appId: {}", appId);
                return false;
            }

            if (application.getStatus() != 0) {
                log.warn("Application status is not 'applied', appId: {}, status: {}", appId, application.getStatus());
                return false;
            }

            application.setStatus(2);
            application.setFeedback(feedback != null ? feedback : "");
            applicationRepo.saveEntity(application);

            Position position = positionRepo.getEntityById(application.getPositionId());
            if (position != null) {
                position.setRejectedNum(position.getRejectedNum() + 1);
                positionRepo.saveEntity(position);
            }

            log.info("Reject application success, appId: {}", appId);
            return true;
        } catch (IOException e) {
            log.error("Reject application failed, appId: {}, error: {}", appId, e.getMessage());
            return false;
        }
    }

    /**
     * Generates a list of weekly period start dates spanning from startDate to endDate.
     * <p>
     * This helper method creates a list of LocalDate objects representing the start of each week
     * (Monday) within the position's duration. Used for workload validation.
     * </p>
     * <p>
     * <b>Algorithm:</b>
     * <ol>
     *   <li>Start from startDate</li>
     *   <li>Add current date to list</li>
     *   <li>Calculate days until next Sunday</li>
     *   <li>Jump to next Monday (Sunday + 1 day)</li>
     *   <li>Repeat until exceeding endDate</li>
     * </ol>
     * </p>
     *
     * @param startDate Position start date
     * @param endDate   Position end date
     * @return List of weekly period start dates (Mondays)
     */
    private List<LocalDate> generateWeeklyPeriods(LocalDate startDate, LocalDate endDate) {
        List<LocalDate> periods = new ArrayList<>();
        
        LocalDate current = startDate;
        
        while (!current.isAfter(endDate)) {
            periods.add(current);
            
            DayOfWeek currentDayOfWeek = current.getDayOfWeek();
            int daysUntilSunday = DayOfWeek.SUNDAY.getValue() - currentDayOfWeek.getValue();
            
            if (daysUntilSunday == 0) {
                daysUntilSunday = 7;
            }
            
            current = current.plusDays(daysUntilSunday + 1);
        }

        return periods;
    }

    /**
     * Checks if adding a new position would exceed a TA's maximum weekly workload.
     * <p>
     * This method performs detailed workload analysis across all weeks of the position duration:
     * <ol>
     *   <li>For each week in the position duration:
     *     <ul>
     *       <li>Calculate week boundaries (Monday to Sunday)</li>
     *       <li>Sum workload from new position + all existing offered positions overlapping that week</li>
     *       <li>If total > maxWeeklyWorkload → exceeds</li>
     *     </ul>
     *   </li>
     * </ol>
     * </p>
     * <p>
     * <b>Overlap Detection:</b> A position overlaps a week if:
     * <pre>
     * weekStart &lt;= positionEnd AND weekEnd &gt;= positionStart
     * </pre>
     * </p>
     * <p>
     * <b>Use Case:</b> Prevents TAs from being overloaded with too many positions,
     * ensuring they can maintain quality work across all commitments.
     * </p>
     *
     * @param offeredApps      List of applications where TA has been offered (status=1)
     * @param newPosition      The new position being considered
     * @param weeklyPeriods    List of weekly period start dates
     * @param maxWeeklyWorkload TA's maximum allowed weekly workload (hours)
     * @return true if workload would be exceeded in any week, false otherwise
     * @throws IOException if loading position data fails
     */
    private boolean checkWorkloadExceeds(List<Application> offeredApps, 
                                         Position newPosition,
                                         List<LocalDate> weeklyPeriods,
                                         float maxWeeklyWorkload) {
        try {
            LocalDate positionEndDate = newPosition.getEndDate().toLocalDateTime().toLocalDate();

            for (LocalDate weekStart : weeklyPeriods) {
                DayOfWeek startDayOfWeek = weekStart.getDayOfWeek();
                int daysUntilSunday = DayOfWeek.SUNDAY.getValue() - startDayOfWeek.getValue();
                
                LocalDate weekEnd = weekStart.plusDays(daysUntilSunday);
                
                if (weekEnd.isAfter(positionEndDate)) {
                    weekEnd = positionEndDate;
                }

                float totalWorkload = newPosition.getWeeklyWorkload();

                for (Application offeredApp : offeredApps) {
                    Position offeredPosition = positionRepo.getEntityById(offeredApp.getPositionId());
                    if (offeredPosition == null) {
                        continue;
                    }

                    LocalDate posStart = offeredPosition.getStartDate().toLocalDateTime().toLocalDate();
                    LocalDate posEnd = offeredPosition.getEndDate().toLocalDateTime().toLocalDate();

                    if (!weekStart.isAfter(posEnd) && !weekEnd.isBefore(posStart)) {
                        totalWorkload += offeredPosition.getWeeklyWorkload();
                    }
                }

                if (totalWorkload > maxWeeklyWorkload) {
                    return true;
                }
            }
            
            return false;
        } catch (IOException e) {
            log.error("Check workload exceeds failed, error message: {}", e.getMessage());
            return false;
        }
    }

    /**
     * Withdraws a position and cleans up all related data.
     * <p>
     * This method performs comprehensive cleanup when an MO cancels a position:
     * <ol>
     *   <li>Sets position status to 3 (withdrawn)</li>
     *   <li>Resets statistics (appliedNum=0, offeredNum=0, rejectedNum=0)</li>
     *   <li>Updates position's updateAt timestamp</li>
     *   <li>Deletes all applications for this position</li>
     *   <li>Deletes the position's portrait</li>
     * </ol>
     * </p>
     * <p>
     * <b>Impact:</b> Withdrawing a position is irreversible and removes all application history.
     * Use with caution. Consider closing (status=2) instead if you want to preserve application data.
     * </p>
     *
     * @param posId ID of the position to withdraw
     * @return true if withdrawal succeeded, false if position not found or IO error occurred
     */
    public boolean withdrawPosition(String posId) {

        try {
            Position position = positionRepo.getEntityById(posId);
            if (position == null) {
                log.warn("position not found, posId: {}", posId);
                return false;
            }

            position.setStatus(3);
            position.setAppliedNum(0);
            position.setOfferedNum(0);
            position.setRejectedNum(0);
            position.setUpdateAt(Timestamp.valueOf(LocalDateTime.now()));
            positionRepo.saveEntity(position);

            // Delete all corresponding applications
            List<Application> applications = applicationRepo.loadAllEntities();
            if (applications != null && !applications.isEmpty()) {
                for (Application app : applications) {
                    if (app != null && posId.equals(app.getPositionId())) {
                        applicationRepo.deleteEntity(app.getId());
                    }
                }
            }

            portraitRepo.deleteEntity(position.getPortraitId());

            log.info("withdraw position success, posId: {}", posId);
            return true;
        } catch (IOException e) {
            log.error("withdraw position failed, posId: {}, error message: {}", posId, e.getMessage());
            return false;
        }
    }
}
