package com.tars.entity.bean;

import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.UUID;

/**
 * Represents a vectorized professional portrait for candidates or positions.
 * <p>
 * This entity stores AI-generated vector embeddings that capture three key dimensions:
 * <ul>
 *   <li><b>Skills</b>: Technical and professional capabilities vector</li>
 *   <li><b>Experience</b>: Work history and achievements vector</li>
 *   <li><b>Soft Skills</b>: Interpersonal and behavioral competencies vector</li>
 * </ul>
 * </p>
 * <p>
 * These vectors enable semantic similarity calculations through cosine similarity,
 * allowing the system to match TA candidates with positions based on conceptual
 * proximity rather than exact keyword matching.
 * </p>
 * <p>
 * <b>Usage:</b>
 * <ul>
 *   <li>Generated by {@link com.tars.ai.PortraitGenerator} from resumes and job descriptions</li>
 *   <li>Compared using {@link com.tars.ai.PortraitMatcher} to calculate match scores</li>
 *   <li>Referenced by {@link Position} and {@link TAProfile} entities</li>
 * </ul>
 * </p>
 * <p>
 * <b>Vector Properties:</b>
 * <ul>
 *   <li>All three vectors should have the same dimension (configured in qwen_config.json)</li>
 *   <li>Typical dimension: 1536 (for text-embedding-v2 model)</li>
 *   <li>Values are normalized floats suitable for cosine similarity calculation</li>
 * </ul>
 * </p>
 *
 * @author Jflame
 * @version 3.0.0
 * @since 2026/4/16
 * @see com.tars.ai.PortraitGenerator
 * @see com.tars.ai.PortraitMatcher
 * @see Position
 * @see TAProfile
 */
@Data
@NoArgsConstructor
public class Portrait {

    /** Unique identifier for the portrait (UUID) */
    private String id;

    /**
     * Vector embedding representing technical and professional skills.
     * <p>
     * Generated from skill lists like ["Java", "Spring Boot", "MySQL"] using
     * the Qwen embedding model. Higher dimensional similarity indicates closer
     * skill alignment between candidate and position.
     * </p>
     */
    private List<Float> skills;

    /**
     * Vector embedding representing work experience and achievements.
     * <p>
     * Generated from narrative experience descriptions (2-4 sentences) that capture:
     * <ul>
     *   <li>Years of relevant experience</li>
     *   <li>Key projects and accomplishments</li>
     *   <li>Domain expertise</li>
     *   <li>Leadership or collaboration experience</li>
     * </ul>
     * </p>
     */
    private List<Float> experience;

    /**
     * Vector embedding representing soft skills and behavioral competencies.
     * <p>
     * Generated from inferred soft skills like ["Communication", "Leadership", "Problem Solving"]
     * based on project descriptions and collaboration mentions in resumes or job descriptions.
     * </p>
     */
    private List<Float> softSkills;

    /**
     * Constructs a Portrait with pre-computed vector embeddings.
     * <p>
     * This constructor is typically called by {@link com.tars.ai.PortraitGenerator}
     * after generating embeddings from text data.
     * </p>
     *
     * @param skillsVector     Vector embedding for technical skills
     * @param experienceVector Vector embedding for work experience
     * @param softSkillsVector Vector embedding for soft skills
     * @throws IllegalArgumentException if any vector is null (vectors can be empty but not null)
     */
    public Portrait(List<Float> skillsVector, List<Float> experienceVector, List<Float> softSkillsVector) {
        this.id = UUID.randomUUID().toString();
        this.skills = skillsVector;
        this.experience = experienceVector;
        this.softSkills = softSkillsVector;
    }
}
