package com.tars.mapper;

import com.tars.entity.bean.Application;
import com.tars.entity.bean.TAProfile;
import com.tars.entity.dto.mo.ApplicationDTO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

/**
 * MapStruct mapper for converting Application and TAProfile entities to MO-facing DTOs.
 * <p>
 * This mapper combines application information with TA candidate profiles to provide
 * Module Owners with applicant details during the review process.
 * </p>
 * <p>
 * <b>Usage:</b> Use the singleton instance {@link #INSTANCE} to perform conversions:
 * <pre>{@code
 * Application app = applicationService.getById(appId);
 * TAProfile profile = taProfileService.getByUserId(app.getUserId());
 * ApplicationDTO dto = AppMapper.INSTANCE.toAppDTO(app, profile);
 * }</pre>
 * </p>
 *
 * @author 477996850
 * @version 1.0.0
 * @since 2026/4/5
 * @see Application
 * @see TAProfile
 * @see ApplicationDTO
 */
@Mapper
public interface AppMapper {

    /** Singleton mapper instance generated by MapStruct */
    AppMapper INSTANCE = Mappers.getMapper(AppMapper.class);

    /**
     * Combines Application and TAProfile entities into an ApplicationDTO for MO application review.
     * <p>
     * This method merges application metadata with TA candidate profile information to provide
     * MOs with essential applicant details for evaluation.
     * </p>
     * <p>
     * <b>Field Mapping:</b>
     * <ul>
     *   <li>{@code appId} ← {@code application.id}</li>
     *   <li>{@code proId} ← {@code taProfile.id}</li>
     *   <li>{@code name} ← {@code taProfile.name}</li>
     *   <li>Profile fields (college, major, degree, year) mapped by name</li>
     *   <li>{@code applyAt} ← {@code application.applyAt}</li>
     *   <li>{@code status} ← {@code application.status}</li>
     * </ul>
     * </p>
     *
     * @param application Source Application entity
     * @param taProfile   Source TAProfile entity
     * @return ApplicationDTO combining application and profile information
     * @see ApplicationDTO
     */
    @Mapping(target = "appId", source = "application.id")
    @Mapping(target = "proId", source = "taProfile.id")
    @Mapping(target = "name", source = "taProfile.name")
    ApplicationDTO toAppDTO(Application application, TAProfile taProfile);
}
