package com.tars.mapper;

import com.tars.entity.bean.Application;
import com.tars.entity.bean.Position;
import com.tars.entity.dto.ta.AppPosDTO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

/**
 * MapStruct mapper for combining Application and Position entities into TA-facing DTOs.
 * <p>
 * This mapper merges data from multiple source entities to create composite DTOs that
 * provide TA users with a unified view of their applications and associated positions.
 * </p>
 * <p>
 * <b>Usage:</b> Use the singleton instance {@link #INSTANCE} to perform conversions:
 * <pre>{@code
 * Application app = applicationService.getById(appId);
 * Position pos = positionService.getById(app.getPositionId());
 * AppPosDTO dto = MultiMapper.INSTANCE.toAppPosDTO(app, pos);
 * }</pre>
 * </p>
 *
 * @author Xiri04
 * @version 1.0.0
 * @since 2026/3/26
 * @see Application
 * @see Position
 * @see AppPosDTO
 */
@Mapper
public interface MultiMapper {

    /** Singleton mapper instance generated by MapStruct */
    MultiMapper INSTANCE = Mappers.getMapper(MultiMapper.class);

    /**
     * Combines Application and Position entities into an AppPosDTO for TA application history display.
     * <p>
     * This method merges application status and timeline with position details to provide
     * TA users with a comprehensive view of their application history.
     * </p>
     * <p>
     * <b>Field Mapping:</b>
     * <ul>
     *   <li>{@code appId} ← {@code application.id}</li>
     *   <li>{@code posId} ← {@code position.id}</li>
     *   <li>{@code status} ← {@code application.status} (application status, not position status)</li>
     *   <li>Position fields (title, moduleCode, moduleName, offeredNum, requiredNum) mapped by name</li>
     *   <li>{@code applyAt} ← {@code application.applyAt}</li>
     * </ul>
     * </p>
     *
     * @param application Source Application entity
     * @param position    Source Position entity
     * @return AppPosDTO combining application and position information
     * @see AppPosDTO
     */
    @Mapping(target = "appId", source = "application.id")
    @Mapping(target = "posId", source = "position.id")
    @Mapping(target = "status", source = "application.status")
    AppPosDTO toAppPosDTO(Application application, Position position);
}
