package com.tars.mapper;

import com.tars.entity.bean.Application;
import com.tars.entity.bean.Position;
import com.tars.entity.dto.ta.PosBriefDTO;
import com.tars.entity.dto.ta.PosDetailDTO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

/**
 * MapStruct mapper for converting Position entities to TA and MO-facing DTOs.
 * <p>
 * This mapper provides conversion methods for different user roles:
 * <ul>
 *   <li><b>TA DTOs</b>: Include application status and ID for tracking application progress</li>
 *   <li><b>MO DTOs</b>: Include vacancy counts and application statistics for management</li>
 * </ul>
 * </p>
 * <p>
 * <b>Usage:</b> Use the singleton instance {@link #INSTANCE} to perform conversions:
 * <pre>{@code
 * // For TA portal
 * PosBriefDTO briefDto = PosMapper.INSTANCE.toTAPosBriefDTO(position, application);
 * 
 * // For MO portal
 * com.tars.entity.dto.mo.PosBriefDTO moBriefDto = PosMapper.INSTANCE.toMOPosBriefDTO(position);
 * }</pre>
 * </p>
 *
 * @author 477996850 Xiri04
 * @version 1.0.0
 * @since 2026/3/30
 * @see Position
 * @see Application
 * @see PosBriefDTO
 * @see PosDetailDTO
 */
@Mapper
public interface PosMapper {

    /** Singleton mapper instance generated by MapStruct */
    PosMapper INSTANCE = Mappers.getMapper(PosMapper.class);

    /**
     * Converts Position and Application entities to a TA-facing brief DTO for position listing.
     * <p>
     * This method combines position summary with application status to help TAs quickly
     * identify which positions they've applied to and their current status.
     * </p>
     * <p>
     * <b>Field Mapping:</b>
     * <ul>
     *   <li>{@code posId} ← {@code position.id}</li>
     *   <li>{@code posStatus} ← {@code position.status}</li>
     *   <li>{@code appId} ← {@code application.id} (null if not applied)</li>
     *   <li>{@code appStatus} ← {@code application.status} (-1 if not applied)</li>
     * </ul>
     * </p>
     *
     * @param position    Source Position entity
     * @param application Source Application entity (may be null if not applied)
     * @return PosBriefDTO for TA position listing
     * @see PosBriefDTO
     */
    @Mapping(target = "posId", source = "position.id")
    @Mapping(target = "posStatus", source = "position.status")
    @Mapping(target = "appId", source = "application.id")
    @Mapping(target = "appStatus", source = "application.status")
    PosBriefDTO toTAPosBriefDTO(Position position, Application application);

    /**
     * Converts Position and Application entities to a TA-facing detailed DTO for position detail view.
     * <p>
     * This method provides comprehensive position information along with application status
     * and feedback for TAs viewing a specific position.
     * </p>
     * <p>
     * <b>Field Mapping:</b>
     * <ul>
     *   <li>{@code posId} ← {@code position.id}</li>
     *   <li>{@code posStatus} ← {@code position.status}</li>
     *   <li>{@code appId} ← {@code application.id} (null if not applied)</li>
     *   <li>{@code appStatus} ← {@code application.status} (-1 if not applied)</li>
     *   <li>All other position fields mapped by name</li>
     * </ul>
     * </p>
     *
     * @param position    Source Position entity
     * @param application Source Application entity (may be null if not applied)
     * @return PosDetailDTO for TA position detail view
     * @see PosDetailDTO
     */
    @Mapping(target = "posId", source = "position.id")
    @Mapping(target = "posStatus", source = "position.status")
    @Mapping(target = "appId", source = "application.id")
    @Mapping(target = "appStatus", source = "application.status")
    PosDetailDTO toTAPosDetailDTO(Position position, Application application);

    /**
     * Converts Position entity to a MO-facing brief DTO for position management listing.
     * <p>
     * This method provides position summary with calculated vacancy and pending application
     * counts for MOs managing their posted positions.
     * </p>
     * <p>
     * <b>Field Mapping:</b>
     * <ul>
     *   <li>{@code posId} ← {@code position.id}</li>
     *   <li>{@code vacancyNum} ← {@code position.requiredNum - position.offeredNum} (calculated)</li>
     *   <li>{@code pendingNum} ← {@code position.appliedNum - position.offeredNum - position.rejectedNum} (calculated)</li>
     *   <li>All other fields mapped by name</li>
     * </ul>
     * </p>
     *
     * @param position Source Position entity
     * @return PosBriefDTO for MO position management
     * @see com.tars.entity.dto.mo.PosBriefDTO
     */
    @Mapping(target = "posId", source = "position.id")
    @Mapping(target = "vacancyNum", expression = "java(position.getRequiredNum() - position.getOfferedNum())")
    @Mapping(target = "pendingNum", expression = "java(position.getAppliedNum() - position.getOfferedNum() - position.getRejectedNum())")
    com.tars.entity.dto.mo.PosBriefDTO toMOPosBriefDTO(Position position);

    /**
     * Converts Position entity to a MO-facing detailed DTO for position detail/edit view.
     * <p>
     * This method provides complete position information including all statistics for MOs
     * to manage and update their posted positions.
     * </p>
     * <p>
     * <b>Field Mapping:</b>
     * <ul>
     *   <li>{@code posId} ← {@code position.id}</li>
     *   <li>All other fields mapped by name (including appliedNum, rejectedNum, etc.)</li>
     * </ul>
     * </p>
     *
     * @param position Source Position entity
     * @return PosDetailDTO for MO position detail view
     * @see com.tars.entity.dto.mo.PosDetailDTO
     */
    @Mapping(target = "posId", source = "position.id")
    com.tars.entity.dto.mo.PosDetailDTO toMOPosDetailDTO(Position position);
}
