package com.tars.mapper;

import com.tars.entity.bean.MOProfile;
import com.tars.entity.bean.TAProfile;
import com.tars.entity.dto.admin.MOProDTO;
import com.tars.entity.dto.admin.TAProDTO;
import com.tars.entity.dto.ta.ProfileDTO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

/**
 * MapStruct mapper for converting TA and MO profile entities to various DTO formats.
 * <p>
 * This mapper provides conversion methods for different contexts:
 * <ul>
 *   <li><b>TA Portal</b>: Profile editing and display ({@link ProfileDTO})</li>
 *   <li><b>MO Portal</b>: Applicant profile review with feedback ({@link com.tars.entity.dto.mo.ProfileDTO})</li>
 *   <li><b>Admin Portal</b>: Profile management for both TA and MO ({@link TAProDTO}, {@link MOProDTO})</li>
 * </ul>
 * </p>
 * <p>
 * <b>Usage:</b> Use the singleton instance {@link #INSTANCE} to perform conversions:
 * <pre>{@code
 * // For TA portal
 * ProfileDTO taDto = ProfileMapper.INSTANCE.toTAProfileDTO(taProfile);
 * 
 * // For MO portal with feedback
 * com.tars.entity.dto.mo.ProfileDTO moDto = ProfileMapper.INSTANCE.toMOProfileDTO(taProfile, "Strong candidate");
 * 
 * // For admin portal
 * TAProDTO adminDto = ProfileMapper.INSTANCE.toProfileDTO(taProfile);
 * }</pre>
 * </p>
 *
 * @author 477996850 wangyue
 * @version 1.0.0
 * @since 2026/3/30
 * @see TAProfile
 * @see MOProfile
 * @see ProfileDTO
 */
@Mapper
public interface ProfileMapper {

    /** Singleton mapper instance generated by MapStruct */
    ProfileMapper INSTANCE = Mappers.getMapper(ProfileMapper.class);

    /**
     * Converts TAProfile entity to a TA-facing DTO for profile editing and display.
     * <p>
     * This method maps personal and academic information for TA users to view and update
     * their own profiles. Excludes internal fields like userId, grade, portraitId, and timestamps.
     * </p>
     *
     * @param taProfile Source TAProfile entity
     * @return ProfileDTO for TA portal
     * @see ProfileDTO
     */
    ProfileDTO toTAProfileDTO(TAProfile taProfile);

    /**
     * Converts TAProfile entity to a MO-facing DTO for applicant review with feedback.
     * <p>
     * This method combines TA profile information with application-specific feedback
     * for MOs evaluating candidates. Includes userId and appId for reference.
     * </p>
     * <p>
     * <b>Note:</b> This method signature uses positional parameters. The feedback parameter
     * is automatically mapped to the {@code feedback} field in the target DTO.
     * </p>
     *
     * @param profile  Source TAProfile entity
     * @param feedback MO's feedback or comments about the applicant
     * @return ProfileDTO for MO portal with feedback
     * @see com.tars.entity.dto.mo.ProfileDTO
     */
    com.tars.entity.dto.mo.ProfileDTO toMOProfileDTO(TAProfile profile, String feedback);

    /**
     * Converts TAProfile entity to an admin-facing DTO for TA profile management.
     * <p>
     * This method provides a simplified view of TA profiles for administrative purposes,
     * excluding fields like grade, portraitId, and maxWeeklyWorkload that are not needed
     * for admin overview.
     * </p>
     *
     * @param profile Source TAProfile entity
     * @return TAProDTO for admin portal
     * @see TAProDTO
     */
    TAProDTO toProfileDTO(TAProfile profile);

    /**
     * Converts MOProfile entity to an admin-facing DTO for MO profile management.
     * <p>
     * This method provides MO profile information for administrative user management.
     * The structure is identical to MOProfile but serves as a dedicated transfer object
     * to decouple the admin API from the domain model.
     * </p>
     *
     * @param profile Source MOProfile entity
     * @return MOProDTO for admin portal
     * @see MOProDTO
     */
    MOProDTO toMOProfileDTO(MOProfile profile);
}
