package com.tars.mapper;

import com.tars.entity.bean.User;
import com.tars.entity.dto.admin.UserDetailDTO;
import com.tars.entity.dto.user.UserDTO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

/**
 * MapStruct mapper for converting {@link User} entities to various DTO formats.
 * <p>
 * This mapper provides conversion methods for:
 * <ul>
 *   <li>User authentication DTO ({@link UserDTO}) for session management</li>
 *   <li>Admin user detail DTO ({@link UserDetailDTO}) for user management pages</li>
 * </ul>
 * </p>
 * <p>
 * <b>Usage:</b> Use the singleton instance {@link #INSTANCE} to perform conversions:
 * <pre>{@code
 * User user = userService.getById(userId);
 * UserDTO dto = UserMapper.INSTANCE.toDTO(user);
 * }</pre>
 * </p>
 *
 * @author JFlame
 * @version 1.0.0
 * @since 2026/3/24
 * @see User
 * @see UserDTO
 * @see UserDetailDTO
 */
@Mapper
public interface UserMapper {

    /** Singleton mapper instance generated by MapStruct */
    UserMapper INSTANCE = Mappers.getMapper(UserMapper.class);

    /**
     * Converts a User entity to a lightweight UserDTO for authentication and session storage.
     * <p>
     * This method maps basic user information (id, name, role, status) while excluding
     * sensitive fields like password and timestamps. The resulting DTO is suitable for
     * storing in HTTP sessions.
     * </p>
     *
     * @param user Source User entity
     * @return UserDTO with basic user information
     * @see UserDTO
     */
    UserDTO toDTO(User user);

    /**
     * Converts a User entity to a detailed UserDetailDTO for admin user management.
     * <p>
     * This method combines user information with an associated profile ID to provide
     * a complete view for administrative operations.
     * </p>
     * <p>
     * <b>Field Mapping:</b>
     * <ul>
     *   <li>{@code userId} ← {@code user.id}</li>
     *   <li>All other fields mapped automatically by name matching</li>
     *   <li>{@code proId} ← provided parameter (TAProfile or MOProfile ID)</li>
     * </ul>
     * </p>
     *
     * @param user  Source User entity
     * @param proId Associated profile ID (from TAProfile or MOProfile)
     * @return UserDetailDTO with complete user information
     * @see UserDetailDTO
     */
    @Mapping(target = "userId", source = "user.id")
    UserDetailDTO toDetailDTO(User user, String proId);
}
